workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build iOS app
        script: |
          xcodebuild -scheme HousekeepingApp -sdk iphoneos -configuration release
    artifacts:
      - build/ios/iphoneos/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/**/*.app
